# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import ProgressBar, PushButton
from qfluentwidgets import IndeterminateProgressBar
from config import cfg, HELP_URL, FEEDBACK_URL,VERSION
from qfluentwidgets import (SettingCardGroup, SwitchSettingCard,
                            OptionsSettingCard,
                            HyperlinkCard, PrimaryPushSettingCard, ScrollArea,
                            VBoxLayout, Theme, InfoBar, CustomColorSettingCard,
                            setTheme, setThemeColor, isDarkTheme)
from qfluentwidgets import DropDownToolButton, TableWidget,Action,RoundMenu,ListWidget, TextEdit, SearchLineEdit
from qfluentwidgets import FluentIcon as FIF,MessageBox
from PyQt5.QtCore import Qt, pyqtSignal, QUrl
from PyQt5.QtGui import QDesktopServices
from PyQt5.QtWidgets import QWidget
from requests import get
from PIL.Image import open as openimg
from re import findall,S
from pyperclip import copy
from threading import Thread


class App_list_widget(ListWidget):
    def __init__(self,parent=None):
        super(App_list_widget,self).__init__(parent)
        self.func=lambda event:()
        self.clicked.connect(self.clicked_singal)
    def set_clicked_func(self,func):
        self.func=func
    def clicked_singal(self):
        try:
            app_name=self.currentItem().text()
            Thread(target=lambda :self.func(app_name)).start()
        except:
            pass
    def addItems(self, labels:list ,show=lambda data:()) -> None:
        show(labels)
        super().addItems(labels)
class Apk_info_frame(QtWidgets.QFrame):
    def __init__(self,parent=None):
        super(Apk_info_frame,self).__init__(parent)
        self.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setObjectName("apk_info_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ScrollArea=ScrollArea(self)
        self.ScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QFrame()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 281, 301))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.real_name = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setFamily("微软雅黑")
        font.setWeight(75)
        font2 = QtGui.QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setFamily('微软雅黑')
        font2.setWeight(75)
        self.real_name.setFont(font)
        self.real_name.setObjectName("real_name")
        self.horizontalLayout_3.addWidget(self.real_name)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pack_name = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pack_name.sizePolicy().hasHeightForWidth())
        self.pack_name.setSizePolicy(sizePolicy)
        self.pack_name.setObjectName("pack_name")
        self.horizontalLayout_4.addWidget(self.pack_name)
        self.pack_copy_btn = PushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pack_copy_btn.sizePolicy().hasHeightForWidth())
        self.pack_copy_btn.setSizePolicy(sizePolicy)
        self.pack_copy_btn.setObjectName("PushButton")
        self.horizontalLayout_4.addWidget(self.pack_copy_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.acitivity_name = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acitivity_name.sizePolicy().hasHeightForWidth())
        self.acitivity_name.setSizePolicy(sizePolicy)
        self.acitivity_name.setObjectName("acitivity_name")
        self.horizontalLayout_5.addWidget(self.acitivity_name)
        self.pack_copy_btn_2 = PushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pack_copy_btn_2.sizePolicy().hasHeightForWidth())
        self.pack_copy_btn_2.setSizePolicy(sizePolicy)
        self.pack_copy_btn_2.setObjectName("PushButton_2")
        self.horizontalLayout_5.addWidget(self.pack_copy_btn_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.highest_ver = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.highest_ver.sizePolicy().hasHeightForWidth())
        self.highest_ver.setSizePolicy(sizePolicy)
        self.highest_ver.setObjectName("highest_ver")
        self.verticalLayout_3.addWidget(self.highest_ver)
        self.lowest_ver = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowest_ver.sizePolicy().hasHeightForWidth())
        self.lowest_ver.setSizePolicy(sizePolicy)
        self.lowest_ver.setObjectName("lowest_ver")
        self.verticalLayout_3.addWidget(self.lowest_ver)
        self.file_size = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_size.sizePolicy().hasHeightForWidth())
        self.file_size.setSizePolicy(sizePolicy)
        self.file_size.setObjectName("file_size")
        self.verticalLayout_3.addWidget(self.file_size)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.ScrollArea)
        self.pack_name.setFont(font2)
        self.acitivity_name.setFont(font2)
        self.highest_ver.setFont(font2)
        self.lowest_ver.setFont(font2)
        self.file_size.setFont(font2)
        self.init()
    def init(self):
        self.pack_copy_btn.setEnabled(False)
        self.pack_copy_btn_2.setEnabled(False)
        self.real_name.setText( "应用名:--")
        self.pack_name.setText( "包名:--")
        self.pack_copy_btn.setText( "复制")
        self.acitivity_name.setText( "activity名:--")
        self.pack_copy_btn_2.setText( "复制")
        self.highest_ver.setText( "最大兼容:--")
        self.lowest_ver.setText( "适配版本:--")
        self.file_size.setText( "文件大小:--")
        self.label.setMaximumSize(70, 70)
        self.label.setPixmap(QtGui.QPixmap("./img/Android.png"))
    def on_load(self):
        self.pack_copy_btn.setEnabled(False)
        self.pack_copy_btn_2.setEnabled(False)
        self.real_name.setText( "应用名:加载中...")
        self.pack_name.setText( "包名:加载中...")
        self.pack_copy_btn.setText( "复制")
        self.acitivity_name.setText( "activity名:加载中...")
        self.pack_copy_btn_2.setText( "复制")
        self.highest_ver.setText( "最大兼容:加载中...")
        self.lowest_ver.setText( "适配版本:加载中...")
        self.file_size.setText( "文件大小:加载中...")
        self.label.setMaximumSize(70, 70)
        self.label.setPixmap(QtGui.QPixmap("./img/Android.png"))
    def copy_package(self):
        copy(self.pack_name.text().replace('包名:',''))
    def copy_activity(self):
        copy(self.acitivity_name.text().replace('activity名:', ''))
    def set_info(self,package,real_name,activity,sdk_ver,highest_ver,size,icon):
        self.real_name.setText(f"应用名:{real_name if real_name!='' else '--'}")
        self.pack_name.setText(f"包名:{package if package!='' else '--'}")
        self.acitivity_name.setText(f"activity名:{activity if activity!='' else '--'}")
        self.highest_ver.setText(f"最大兼容:{highest_ver if highest_ver!='' else '--'}")
        self.lowest_ver.setText(f"适配版本:{sdk_ver if sdk_ver!='' else '--'}")
        self.file_size.setText(f"文件大小:{size if size!='' else '--'}")
        if package=='':
            self.pack_copy_btn.setEnabled(False)
        else:
            self.pack_copy_btn.setEnabled(True)
            self.pack_copy_btn.clicked.connect(self.copy_package)
        if activity=='':
            self.pack_copy_btn_2.setEnabled(False)
        else:
            self.pack_copy_btn_2.setEnabled(True)
            self.pack_copy_btn_2.clicked.connect(self.copy_activity)
        self.label.setMaximumSize(70,70)
        try:
            img=openimg(icon)
            icon=QtGui.QPixmap(icon if icon!='' else "./img/Android.png")
        except:
            icon=QtGui.QPixmap("./img/Android.png")
        self.label.setPixmap(icon)
class Apk_Path_TabelWidget(TableWidget):
    def __init__(self, parent=None,mouse_press_func=lambda row:()):
        super(Apk_Path_TabelWidget, self).__init__(parent)
        self.setAcceptDrops(True)
        self.setColumnWidth(1,self.width()-100)
        self.clicked.connect(self.mousePress)
        self.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.mousePressFunc=mouse_press_func
    def set_mouse_press_func(self,func):
        self.mousePressFunc=func
    def generateMenu(self,pos):
        pos=self.mapToGlobal(pos)
        if self.selectedItems()!=[]:
            menu=RoundMenu()
            menu.addActions([Action('删除'),Action('清空'),Action('提示路径'),Action('解析')])
            menu.exec(pos)
    def dragEnterEvent(self, event):
        if event.mimeData().hasUrls():
            event.acceptProposedAction()

    def dragMoveEvent(self, event):
        event.acceptProposedAction()

    def dropEvent(self, event):
        if event.mimeData().hasUrls():
            event.acceptProposedAction()
            urls = event.mimeData().urls()
            for url in urls:
                file_path = url.toLocalFile()
                if file_path.lower().endswith('.apk'):
                    self.add_apk_row(file_path)

    def mousePress(self,event=None) -> None:
        row = self.currentRow()
        text=self.item(row,1).text()
        t=Thread(target=lambda :self.mousePressFunc(text))
        t.start()
    def add_apk_row(self, file_path):
        row_count = self.rowCount()
        self.insertRow(row_count)

        file_name = QtCore.QFileInfo(file_path).fileName()
        item_file_name = QtWidgets.QTableWidgetItem(file_name)
        self.setItem(row_count, 0, item_file_name)

        item_file_path = QtWidgets.QTableWidgetItem(file_path)
        self.setItem(row_count, 1, item_file_path)
class Home_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(830, 572)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ScrollArea = ScrollArea(Form)
        self.ScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QFrame()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 830, 770))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents_main")
        self.verticalLayout_4 = VBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0,0,0,0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.info_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.info_frame.setMinimumSize(QtCore.QSize(0, 140))
        self.info_frame.setMaximumSize(QtCore.QSize(16777215, 140))
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.info_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.info_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.info_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.info_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.info_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.info_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.info_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.info_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ComboBox = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox.sizePolicy().hasHeightForWidth())
        self.ComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.ComboBox.setFont(font)
        self.ComboBox.setObjectName("ComboBox")
        self.horizontalLayout.addWidget(self.ComboBox)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.info_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.info_frame)
        self.battery_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.battery_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.battery_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.battery_frame.setStyleSheet("")
        self.battery_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.battery_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.battery_frame.setObjectName("battery_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.battery_frame)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.battery_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.battery_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.battery_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.ProgressBar = ProgressBar(self.battery_frame)
        self.ProgressBar.setMaximum(100)
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setObjectName("ProgressBar")
        self.gridLayout_2.addWidget(self.ProgressBar, 3, 0, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.battery_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.battery_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 4, 1, 1)
        self.verticalLayout_4.addWidget(self.battery_frame)
        self.screen_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.screen_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.screen_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.screen_frame.setStyleSheet("")
        self.screen_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.screen_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.screen_frame.setObjectName("screen_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.screen_frame)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setHorizontalSpacing(5)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_22 = QtWidgets.QLabel(self.screen_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.screen_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.screen_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.screen_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.screen_frame)
        self.sdcard_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.sdcard_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.sdcard_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.sdcard_frame.setStyleSheet("")
        self.sdcard_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sdcard_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sdcard_frame.setObjectName("sdcard_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sdcard_frame)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setHorizontalSpacing(5)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtWidgets.QLabel(self.sdcard_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.ProgressBar_2 = ProgressBar(self.sdcard_frame)
        self.ProgressBar_2.setMaximum(100)
        self.ProgressBar_2.setProperty("value", 0)
        self.ProgressBar_2.setObjectName("ProgressBar_2")
        self.gridLayout_3.addWidget(self.ProgressBar_2, 3, 0, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.sdcard_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.sdcard_frame)
        self.root_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.root_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.root_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.root_frame.setStyleSheet("")
        self.root_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.root_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.root_frame.setObjectName("root_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.root_frame)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setHorizontalSpacing(5)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.root_frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.ProgressBar_3 = ProgressBar(self.root_frame)
        self.ProgressBar_3.setMaximum(100)
        self.ProgressBar_3.setProperty("value", 0)
        self.ProgressBar_3.setObjectName("ProgressBar_3")
        self.gridLayout_4.addWidget(self.ProgressBar_3, 3, 0, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.root_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 3, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.root_frame)
        self.func_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.func_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.func_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.func_frame.setObjectName("func_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.func_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.func_app = QtWidgets.QFrame(self.func_frame)
        self.func_app.setMinimumSize(QtCore.QSize(0, 150))
        self.func_app.setMaximumSize(QtCore.QSize(16777215, 150))
        self.func_app.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.func_app.setFrameShadow(QtWidgets.QFrame.Raised)
        self.func_app.setObjectName("func_app")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.func_app)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(40)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.PushButton_3 = PushButton(self.func_app)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.PushButton_3.setFont(font)
        self.PushButton_3.setIcon(FIF.MARKET)
        self.PushButton_3.setObjectName("PushButton_3")
        self.gridLayout_6.addWidget(self.PushButton_3, 4, 0, 1, 1)
        self.PushButton_4 = PushButton(self.func_app)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.PushButton_4.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/keyboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PushButton_4.setIcon(icon)
        self.PushButton_4.setObjectName("PushButton_4")
        self.gridLayout_6.addWidget(self.PushButton_4, 4, 1, 1, 1)
        self.title_app = QtWidgets.QLabel(self.func_app)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_app.sizePolicy().hasHeightForWidth())
        self.title_app.setSizePolicy(sizePolicy)
        self.title_app.setMinimumSize(QtCore.QSize(0, 30))
        self.title_app.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.title_app.setFont(font)
        self.title_app.setObjectName("title_app")
        self.gridLayout_6.addWidget(self.title_app, 0, 0, 1, 2)
        self.PushButton = PushButton(self.func_app)
        self.PushButton.setIcon(FIF.DOWNLOAD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButton.sizePolicy().hasHeightForWidth())
        self.PushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.PushButton.setFont(font)
        self.PushButton.setObjectName("PushButton")
        self.gridLayout_6.addWidget(self.PushButton, 1, 0, 1, 1)
        self.PushButton_2 = PushButton(self.func_app)
        self.PushButton_2.setIcon(FIF.APPLICATION)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.PushButton_2.setFont(font)
        self.PushButton_2.setObjectName("PushButton_2")
        self.gridLayout_6.addWidget(self.PushButton_2, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.func_app)
        self.func_xtc = QtWidgets.QFrame(self.func_frame)
        self.func_xtc.setMinimumSize(QtCore.QSize(0, 150))
        self.func_xtc.setMaximumSize(QtCore.QSize(16777215, 150))
        self.func_xtc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.func_xtc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.func_xtc.setObjectName("func_xtc")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.func_xtc)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_7.setHorizontalSpacing(40)
        self.gridLayout_7.setVerticalSpacing(14)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.PushButton_5 = PushButton(self.func_xtc)
        self.PushButton_5.setIcon(FIF.FIT_PAGE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.PushButton_5.setFont(font)
        self.PushButton_5.setObjectName("PushButton_5")
        self.gridLayout_7.addWidget(self.PushButton_5, 1, 0, 1, 1)
        self.title_xtc = QtWidgets.QLabel(self.func_xtc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_xtc.sizePolicy().hasHeightForWidth())
        self.title_xtc.setSizePolicy(sizePolicy)
        self.title_xtc.setMinimumSize(QtCore.QSize(0, 30))
        self.title_xtc.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.title_xtc.setFont(font)
        self.title_xtc.setObjectName("title_xtc")
        self.gridLayout_7.addWidget(self.title_xtc, 0, 0, 1, 2)
        self.PushButton_6 = PushButton(self.func_xtc)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.PushButton_6.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/battery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PushButton_6.setIcon(icon1)
        self.PushButton_6.setObjectName("PushButton_6")
        self.gridLayout_7.addWidget(self.PushButton_6, 1, 1, 1, 1)
        self.PushButton_7 = PushButton(self.func_xtc)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.PushButton_7.setFont(font)
        self.PushButton_7.setIcon(FIF.FOLDER)
        self.PushButton_7.setObjectName("PushButton_7")
        self.gridLayout_7.addWidget(self.PushButton_7, 2, 0, 1, 1)
        self.PushButton_8 = PushButton(self.func_xtc)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.PushButton_8.setFont(font)
        self.PushButton_8.setIcon(FIF.COMMAND_PROMPT)
        self.PushButton_8.setObjectName("PushButton_8")
        self.gridLayout_7.addWidget(self.PushButton_8, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.verticalLayout.addWidget(self.func_xtc)
        self.verticalLayout_4.addWidget(self.func_frame)
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.ScrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label_6.setText(_translate("Form", "安卓版本: --"))
        self.label_7.setText(_translate("Form", "root权限: --"))
        self.label_2.setText(_translate("Form", "设备名称: --"))
        self.label_9.setText(_translate("Form", "安卓ID: --"))
        self.label_4.setText(_translate("Form", "设备产商: --"))
        self.label_5.setText(_translate("Form", "mac地址: --"))
        self.label_8.setText(_translate("Form", "应用数量: --"))
        self.label.setText(_translate("Form", "设备:--"))
        self.label_3.setText(_translate("Form", "设备型号: --"))
        self.label_12.setText(_translate("Form", "电压: --"))
        self.label_13.setText(_translate("Form", "温度: --"))
        self.label_11.setText(_translate("Form", "USB: --"))
        self.label_10.setText(_translate("Form", "当前电量: --"))
        self.label_19.setText(_translate("Form", "-%"))
        self.label_22.setText(_translate("Form", "当前DPI: --"))
        self.label_14.setText(_translate("Form", "当前屏幕大小: --"))
        self.label_21.setText(_translate("Form", "默认DPI: --"))
        self.label_20.setText(_translate("Form", "默认屏幕大小: --"))
        self.label_15.setText(_translate("Form", "内部储存: --/--"))
        self.label_16.setText(_translate("Form", "-%"))
        self.label_17.setText(_translate("Form", "根目录: --/--"))
        self.label_18.setText(_translate("Form", "-%"))
        self.PushButton_3.setText(_translate("Form", "进程管理"))
        self.PushButton_4.setText(_translate("Form", "输入法管理"))
        self.title_app.setText(_translate("Form", "应用专区-共4种功能"))
        self.PushButton.setText(_translate("Form", "安装应用"))
        self.PushButton_2.setText(_translate("Form", "应用管理"))
        self.PushButton_5.setText(_translate("Form", "屏幕设置"))
        self.title_xtc.setText(_translate("Form", "设备管理-共4种功能"))
        self.PushButton_6.setText(_translate("Form", "充电管理"))
        self.PushButton_7.setText(_translate("Form", "文件管理"))
        self.PushButton_8.setText(_translate("Form", "root工具"))
    def init_info(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_6.setText(_translate("Form", "安卓版本: --"))
        self.label_7.setText(_translate("Form", "root权限: --"))
        self.label_2.setText(_translate("Form", "设备名称: --"))
        self.label_9.setText(_translate("Form", "安卓ID: --"))
        self.label_4.setText(_translate("Form", "设备产商: --"))
        self.label_5.setText(_translate("Form", "mac地址: --"))
        self.label_8.setText(_translate("Form", "应用数量: --"))
        self.label.setText(_translate("Form", "设备:--"))
        self.label_3.setText(_translate("Form", "设备型号: --"))
        self.label_12.setText(_translate("Form", "电压: --"))
        self.label_13.setText(_translate("Form", "温度: --"))
        self.label_11.setText(_translate("Form", "USB: --"))
        self.label_10.setText(_translate("Form", "当前电量: --"))
        self.label_19.setText(_translate("Form", "-%"))
        self.label_22.setText(_translate("Form", "当前DPI: --"))
        self.label_14.setText(_translate("Form", "当前屏幕大小: --"))
        self.label_21.setText(_translate("Form", "默认DPI: --"))
        self.label_20.setText(_translate("Form", "默认屏幕大小: --"))
        self.label_15.setText(_translate("Form", "内部储存: --/--"))
        self.label_16.setText(_translate("Form", "-%"))
        self.label_17.setText(_translate("Form", "根目录: --/--"))
        self.label_18.setText(_translate("Form", "-%"))
        self.ProgressBar.setValue(0)
        self.ProgressBar_2.setValue(0)
        self.ProgressBar_3.setValue(0)

class Welcome_Window():
    def setupUi(self, Form):
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Form.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint | QtCore.Qt.FramelessWindowHint | QtCore.Qt.SplashScreen)
        Form.setObjectName("Form")
        Form.resize(680, 480)
        Form.setMinimumSize(QtCore.QSize(680, 480))
        Form.setMaximumSize(QtCore.QSize(680, 480))
        if isDarkTheme():
            Form.setStyleSheet(".QFrame{background-color:rgba(39, 39, 39);border-radius:30px}\nQLabel{color:white}")
        else:
            Form.setStyleSheet(".QFrame{background-color:white;border-radius:30px}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(230, 30, 201, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./img/ico.png"))
        self.label.setObjectName("label")
        self.IndeterminateProgressBar = IndeterminateProgressBar(self.frame)
        self.IndeterminateProgressBar.setGeometry(QtCore.QRect(190, 380, 311, 4))
        self.IndeterminateProgressBar.setObjectName("IndeterminateProgressBar")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(250, 280, 181, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "welcome"))
        self.label_2.setText(_translate("Form", "welcome back!"))

class SettingInterface(ScrollArea):
    """ Setting interface """

    acrylicEnableChanged = pyqtSignal(bool)
    checkUpdateSig = pyqtSignal()
    minimizeToTrayChanged = pyqtSignal(bool)

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.scrollWidget = QWidget()
        self.expandLayout = VBoxLayout(self.scrollWidget)

        # personalization
        self.personalGroup = SettingCardGroup(self.tr('个性化'), self.scrollWidget)
        self.enableAcrylicCard = SwitchSettingCard(
            FIF.TRANSPARENT,
            self.tr("使用亚克力效果"),
            self.tr("亚克力效果有更好的视觉体验，但可能会导致窗户卡住"),
            configItem=cfg.enableAcrylicBackground,
            parent=self.personalGroup
        )
        self.themeCard = OptionsSettingCard(
            cfg.themeMode,
            FIF.BRUSH,
            self.tr('应用主题'),
            self.tr("更改应用程序的外观"),
            texts=[
                self.tr('浅色'), self.tr('深色'),
                self.tr('使用系统默认外观')
            ],
            parent=self.personalGroup
        )
        self.themeColorCard=CustomColorSettingCard(
            cfg.themeColor,
            FIF.PALETTE,
            self.tr('主题颜色'),
            self.tr('更改应用程序的主题颜色'),
            self.personalGroup
        )
        self.zoomCard = OptionsSettingCard(
            cfg.dpiScale,
            FIF.ZOOM,
            self.tr("界面缩放(DPI)"),
            self.tr("更改小部件和字体的大小"),
            texts=[
                "100%", "125%", "150%", "175%", "200%",
                self.tr("使用系统默认DPI")
            ],
            parent=self.personalGroup
        )

        # main panel
        self.mainPanelGroup = SettingCardGroup(self.tr('主面板'), self.scrollWidget)
        self.minimizeToTrayCard = SwitchSettingCard(
            FIF.MINIMIZE,
            self.tr('托盘服务'),
            self.tr('小天才专用工具箱将在系统托盘中运行'),
            configItem=cfg.minimizeToTray,
            parent=self.mainPanelGroup
        )

        # update software
        self.updateSoftwareGroup = SettingCardGroup(self.tr("软件更新"), self.scrollWidget)
        self.updateOnStartUpCard = SwitchSettingCard(
            FIF.UPDATE,
            self.tr('在应用程序启动时检查更新'),
            self.tr('新版本将更加稳定，并具有更多功能'),
            configItem=cfg.checkUpdateAtStartUp,
            parent=self.updateSoftwareGroup
        )

        # application
        self.aboutGroup = SettingCardGroup(self.tr('关于'), self.scrollWidget)
        self.helpCard = HyperlinkCard(
            HELP_URL,
            self.tr('打开帮助页面'),
            FIF.HELP,
            self.tr('帮助'),
            self.tr('发现新功能并了解有关小天才专用工具箱的有用提示'),
            self.aboutGroup
        )
        self.feedbackCard = PrimaryPushSettingCard(
            self.tr('作者B站'),
            FIF.FEEDBACK,
            self.tr('作者B站'),
            self.tr('观看作者的相关视频'),
            self.aboutGroup
        )
        self.aboutCard = PrimaryPushSettingCard(
            self.tr('检查更新'),
            FIF.INFO,
            self.tr('关于'),
            '小天才专用工具箱V'+str(VERSION)+'\n(此工具永久免费,没有任何商业目的,同时也没有Qt的商业许可证)',
        self.aboutGroup
        )

        self.__initWidget()

    def __initWidget(self):
        self.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.setViewportMargins(0, 0, 0, 0)
        self.setWidget(self.scrollWidget)
        self.setWidgetResizable(True)

        # initialize style sheet
        self.setQss()

        # initialize layout
        self.__initLayout()
        self.__connectSignalToSlot()

    def __initLayout(self):

        # add cards to group
        self.personalGroup.addSettingCard(self.enableAcrylicCard)
        self.personalGroup.addSettingCard(self.themeCard)
        self.personalGroup.addSettingCard(self.themeColorCard)
        self.personalGroup.addSettingCard(self.zoomCard)

        self.updateSoftwareGroup.addSettingCard(self.updateOnStartUpCard)

        self.mainPanelGroup.addSettingCard(self.minimizeToTrayCard)

        self.aboutGroup.addSettingCard(self.helpCard)
        self.aboutGroup.addSettingCard(self.feedbackCard)
        self.aboutGroup.addSettingCard(self.aboutCard)

        # add setting card group to layout
        self.expandLayout.setSpacing(0)
        self.expandLayout.setContentsMargins(0, 0, 0, 0)
        self.expandLayout.addWidget(self.personalGroup)
        self.expandLayout.addWidget(self.mainPanelGroup)
        self.expandLayout.addWidget(self.updateSoftwareGroup)
        self.expandLayout.addWidget(self.aboutGroup)

    def setQss(self):
        """ set style sheet """
        self.scrollWidget.setObjectName('scrollWidget')

        theme = 'dark' if isDarkTheme() else 'light'
        with open(f'style/{theme}/setting_interface.qss', encoding='utf-8') as f:
            self.setStyleSheet(f.read())

    def __showRestartTooltip(self):
        """ show restart tooltip """
        InfoBar.success(
            '设置成功!',
            self.tr('重新启动软件以生效'),
            parent=self.window()
        )

    def onThemeChanged(self, theme: Theme):
        """ theme changed slot """
        # change the theme of qfluentwidgets
        setTheme(theme)

        # chang the theme of setting interface
        self.setQss()

    def __connectSignalToSlot(self):
        """ connect signal to slot """
        cfg.appRestartSig.connect(self.__showRestartTooltip)
        cfg.themeChanged.connect(self.onThemeChanged)


        # personalization
        self.enableAcrylicCard.checkedChanged.connect(
            self.acrylicEnableChanged)
        self.themeColorCard.colorChanged.connect(setThemeColor)

        # main panel
        self.minimizeToTrayCard.checkedChanged.connect(
            self.minimizeToTrayChanged)

        # about
        self.aboutCard.clicked.connect(self.check_update)
        self.feedbackCard.clicked.connect(
            lambda: QDesktopServices.openUrl(QUrl(FEEDBACK_URL)))

    def check_update(self):
        try:
            res = get("https://wwtw.lanzouq.com/b04ewllad/")
            ver = findall(r'<div class="d" id="info">.*?<div id="filename">小天才专用工具箱</div>.*?<div id="infos">.*?<div id="ready" style="background:#ccc; ">.*?<div id="name".*?<a href="https://lanqinyun.com/.*?>Setup_(?P<ver>.*?).exe</a> </div>',res.text,S)
            k = 0
            for i in ver:
                v = str(i).replace("_", ".")
                if float(v) > k:
                    k = float(v)
            if k > float(VERSION):
                m = MessageBox(title="有新版本!",
                               content="检测到新版本:小天才专用工具箱V{},快去更新体验最新功能吧!".format(str(k)),
                               parent=self.parent().parent())
                m.yesButton.setText("立即更新")
                m.cancelButton.setText("暂不更新")
                if m.exec():
                    QDesktopServices.openUrl(QUrl("https://lanqinyun.com/s/MbmumeKkui"))
            else:
                m = MessageBox(title="已是最新版本了",
                               content="当前小天才专用工具箱V{}是最新版本".format(VERSION),
                               parent=self.parent().parent())
                m.yesButton.setText("确认")
                m.cancelButton.setText("取消")
                m.exec()
        except Exception as e:
            print(e)
class Apk_Install_Window(object):
    def __init__(self):
        self.apk_path_dict=dict()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(649, 630)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0,3,0,0)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.push_lock_btn = PushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_lock_btn.sizePolicy().hasHeightForWidth())
        self.push_lock_btn.setSizePolicy(sizePolicy)
        self.push_lock_btn.setObjectName("push_lock_btn")
        self.horizontalLayout_2.addWidget(self.push_lock_btn)
        self.install_btn = DropDownToolButton(Form)
        self.install_menu=RoundMenu()
        self.action1=Action('通用模式')
        self.action2=Action('ROOT模式')
        self.action3=Action('PM模式')
        self.actionGroup1 = QtWidgets.QActionGroup(self.install_menu)
        self.actionGroup1.addAction(self.action1)
        self.actionGroup1.addAction(self.action2)
        self.actionGroup1.addAction(self.action3)
        self.install_menu.addActions([self.action1,self.action2,self.action3])
        self.install_btn.setMenu(self.install_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.install_btn.sizePolicy().hasHeightForWidth())
        self.install_btn.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("CCC")
        self.install_btn.setIcon(icon)
        self.install_btn.setIconSize(QtCore.QSize(1, 1))
        self.install_btn.setObjectName("install_btn")
        self.horizontalLayout_2.addWidget(self.install_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("table_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget = Apk_Path_TabelWidget(self.frame_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnWidth(1,300)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PushButton_3 = PushButton(self.frame_2)
        self.PushButton_3.setObjectName("PushButton_3")
        self.horizontalLayout.addWidget(self.PushButton_3)
        self.PushButton_4 = PushButton(self.frame_2)
        self.PushButton_4.setObjectName("PushButton_4")
        self.horizontalLayout.addWidget(self.PushButton_4)
        self.PushButton_5 = PushButton(self.frame_2)
        self.PushButton_5.setObjectName("PushButton_5")
        self.horizontalLayout.addWidget(self.PushButton_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.apk_info=Apk_info_frame(parent=self.frame)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_6.addWidget(self.apk_info)
        self.data_text = TextEdit(Form)
        self.data_text.setEnabled(True)
        self.data_text.setDocumentTitle("")
        self.data_text.setReadOnly(True)
        self.data_text.setObjectName("data_text")
        self.verticalLayout.addWidget(self.data_text)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.push_lock_btn.setText(_translate("Form", "解PUSH锁"))
        self.PushButton_3.setText(_translate("Form", "+"))
        self.PushButton_4.setText(_translate("Form", "-"))
        self.PushButton_5.setText(_translate("Form", "清空"))
        self.data_text.setPlaceholderText(_translate("Form", "安装数据..."))
        self.install_btn.setText('安装模式')
        self.tableWidget.setHorizontalHeaderLabels(['文件名', '路径'])
        self.PushButton_5.clicked.connect(lambda :(self.tableWidget.setRowCount(0),self.tableWidget.setColumnCount(2),self.tableWidget.setHorizontalHeaderLabels(['文件名','路径'])))
class App_List_Widget(object):
    def __init__(self):
        a=[]
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(651, 584)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.app_search = QtWidgets.QGroupBox(Frame)
        self.app_search.setObjectName("app_search")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.app_search)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_edit = SearchLineEdit(self.app_search)
        self.search_edit.setObjectName("search_edit")
        self.horizontalLayout_4.addWidget(self.search_edit)
        self.verticalLayout_3.addWidget(self.app_search)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setContentsMargins(0,0,0,0)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ListWidget = App_list_widget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListWidget.sizePolicy().hasHeightForWidth())
        self.ListWidget.setSizePolicy(sizePolicy)
        self.ListWidget.setObjectName("ListWidget")
        self.verticalLayout_4.addWidget(self.ListWidget)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.app_frame = Apk_info_frame(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.app_frame.sizePolicy().hasHeightForWidth())
        self.app_frame.setSizePolicy(sizePolicy)
        self.app_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_frame.setObjectName("app_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.app_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2.addWidget(self.app_frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.show_mode = QtWidgets.QGroupBox(self.frame)
        self.show_mode.setObjectName("show_mode")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.show_mode)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.flush_system = PushButton(self.show_mode)
        self.flush_system.setObjectName("flush_system")
        self.horizontalLayout.addWidget(self.flush_system)
        self.flush_3 = PushButton(self.show_mode)
        self.flush_3.setObjectName("flush_3")
        self.horizontalLayout.addWidget(self.flush_3)
        self.flush_all = PushButton(self.show_mode)
        self.flush_all.setObjectName("flush_all")
        self.horizontalLayout.addWidget(self.flush_all)
        self.verticalLayout.addWidget(self.show_mode)
        self.app_func = QtWidgets.QGroupBox(self.frame)
        self.app_func.setObjectName("app_func")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.app_func)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.freeze_on = PushButton(self.app_func)
        self.freeze_on.setObjectName("freeze_on")
        self.horizontalLayout_3.addWidget(self.freeze_on)
        self.freeze_off = PushButton(self.app_func)
        self.freeze_off.setObjectName("freeze_off")
        self.horizontalLayout_3.addWidget(self.freeze_off)
        self.start_app = PushButton(self.app_func)
        self.start_app.setObjectName("start_app")
        self.horizontalLayout_3.addWidget(self.start_app)
        self.uninstall_app = PushButton(self.app_func)
        self.uninstall_app.setObjectName("uninstall_app")
        self.horizontalLayout_3.addWidget(self.uninstall_app)
        self.get_apk = PushButton(self.app_func)
        self.get_apk.setObjectName("get_apk")
        self.horizontalLayout_3.addWidget(self.get_apk)
        self.verticalLayout.addWidget(self.app_func)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frame)
        self.TextEdit = TextEdit(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextEdit.sizePolicy().hasHeightForWidth())
        self.TextEdit.setSizePolicy(sizePolicy)
        self.TextEdit.setReadOnly(True)
        self.TextEdit.setObjectName("TextEdit")
        self.verticalLayout_3.addWidget(self.TextEdit)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
    def set_search(self,apk_list:list):
        self.completer = QtWidgets.QCompleter(apk_list, self.search_edit)
        self.completer.setCaseSensitivity(Qt.CaseInsensitive)
        self.completer.setMaxVisibleItems(10)
        self.completer.setFilterMode(QtCore.Qt.MatchContains)
        self.search_edit.setCompleter(self.completer)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.app_search.setTitle(_translate("Frame", "快速查找"))
        self.show_mode.setTitle(_translate("Frame", "显示模式"))
        self.flush_system.setText(_translate("Frame", "显示系统应用"))
        self.flush_3.setText(_translate("Frame", "显示第三方应用"))
        self.flush_all.setText(_translate("Frame", "显示所有应用"))
        self.app_func.setTitle(_translate("Frame", "应用功能"))
        self.freeze_on.setText(_translate("Frame", "冻结应用"))
        self.freeze_off.setText(_translate("Frame", "解冻应用"))
        self.start_app.setText(_translate("Frame", "启动应用"))
        self.uninstall_app.setText(_translate("Frame", "卸载应用"))
        self.get_apk.setText(_translate("Frame", "提取应用"))
        self.TextEdit.setPlaceholderText(_translate("Frame", "操作数据..."))
class Ps_list(object):
    def setupUi(self, ps_list):
        ps_list.setObjectName("ps_list")
        ps_list.resize(624, 647)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ps_list)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.app_search = QtWidgets.QGroupBox(ps_list)
        self.app_search.setObjectName("app_search")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.app_search)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_edit = SearchLineEdit(self.app_search)
        self.search_edit.setObjectName("search_edit")
        self.horizontalLayout_4.addWidget(self.search_edit)
        self.verticalLayout_3.addWidget(self.app_search)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(ps_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ListWidget = App_list_widget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListWidget.sizePolicy().hasHeightForWidth())
        self.ListWidget.setSizePolicy(sizePolicy)
        self.ListWidget.setObjectName("ListWidget")
        self.verticalLayout_4.addWidget(self.ListWidget)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.app_frame = Apk_info_frame(ps_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.app_frame.sizePolicy().hasHeightForWidth())
        self.app_frame.setSizePolicy(sizePolicy)
        self.app_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_frame.setObjectName("app_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.app_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2.addWidget(self.app_frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(ps_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.show_mode = QtWidgets.QGroupBox(self.frame)
        self.show_mode.setObjectName("show_mode")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.show_mode)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.flush_system = PushButton(self.show_mode)
        self.flush_system.setObjectName("flush_system")
        self.horizontalLayout.addWidget(self.flush_system)
        self.flush_3 = PushButton(self.show_mode)
        self.flush_3.setObjectName("flush_3")
        self.horizontalLayout.addWidget(self.flush_3)
        self.flush_all = PushButton(self.show_mode)
        self.flush_all.setObjectName("flush_all")
        self.horizontalLayout.addWidget(self.flush_all)
        self.verticalLayout.addWidget(self.show_mode)
        self.app_func = QtWidgets.QGroupBox(self.frame)
        self.app_func.setObjectName("app_func")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.app_func)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.kill_ps = PushButton(self.app_func)
        self.kill_ps.setObjectName("kill_ps")
        self.horizontalLayout_3.addWidget(self.kill_ps)
        self.kill_all = PushButton(self.app_func)
        self.kill_all.setObjectName("kill_all")
        self.horizontalLayout_3.addWidget(self.kill_all)
        self.verticalLayout.addWidget(self.app_func)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frame)
        self.TextEdit = TextEdit(ps_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextEdit.sizePolicy().hasHeightForWidth())
        self.TextEdit.setSizePolicy(sizePolicy)
        self.TextEdit.setReadOnly(True)
        self.TextEdit.setObjectName("TextEdit")
        self.verticalLayout_3.addWidget(self.TextEdit)

        self.retranslateUi(ps_list)
        QtCore.QMetaObject.connectSlotsByName(ps_list)

    def retranslateUi(self, ps_list):
        _translate = QtCore.QCoreApplication.translate
        ps_list.setWindowTitle(_translate("ps_list", "Frame"))
        self.app_search.setTitle(_translate("ps_list", "快速查找"))
        self.show_mode.setTitle(_translate("ps_list", "显示模式"))
        self.flush_system.setText(_translate("ps_list", "显示系统进程"))
        self.flush_3.setText(_translate("ps_list", "显示第三方进程"))
        self.flush_all.setText(_translate("ps_list", "显示所有进程"))
        self.app_func.setTitle(_translate("ps_list", "应用功能"))
        self.kill_ps.setText(_translate("ps_list", "杀死进程"))
        self.kill_all.setText(_translate("ps_list", "杀死全部进程"))
        self.TextEdit.setPlaceholderText(_translate("ps_list", "操作数据..."))
    def set_search(self,ps_list:list):
        self.completer = QtWidgets.QCompleter(ps_list, self.search_edit)
        self.completer.setCaseSensitivity(Qt.CaseInsensitive)
        self.completer.setMaxVisibleItems(10)
        self.completer.setFilterMode(QtCore.Qt.MatchContains)
        self.search_edit.setCompleter(self.completer)
class Input_list(object):
    def setupUi(self, ps_list):
        ps_list.setObjectName("ps_list")
        ps_list.resize(624, 647)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ps_list)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.app_search = QtWidgets.QGroupBox(ps_list)
        self.app_search.setObjectName("app_search")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.app_search)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_edit = SearchLineEdit(self.app_search)
        self.search_edit.setObjectName("search_edit")
        self.horizontalLayout_4.addWidget(self.search_edit)
        self.verticalLayout_3.addWidget(self.app_search)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(ps_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ListWidget = App_list_widget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListWidget.sizePolicy().hasHeightForWidth())
        self.ListWidget.setSizePolicy(sizePolicy)
        self.ListWidget.setObjectName("ListWidget")
        self.verticalLayout_4.addWidget(self.ListWidget)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.app_frame = Apk_info_frame(ps_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.app_frame.sizePolicy().hasHeightForWidth())
        self.app_frame.setSizePolicy(sizePolicy)
        self.app_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_frame.setObjectName("app_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.app_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2.addWidget(self.app_frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.PushButton = PushButton(ps_list)
        self.PushButton.setObjectName("PushButton")
        self.verticalLayout_3.addWidget(self.PushButton)
        self.frame = QtWidgets.QFrame(ps_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frame)
        self.TextEdit = TextEdit(ps_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextEdit.sizePolicy().hasHeightForWidth())
        self.TextEdit.setSizePolicy(sizePolicy)
        self.TextEdit.setReadOnly(True)
        self.TextEdit.setObjectName("TextEdit")
        self.verticalLayout_3.addWidget(self.TextEdit)

        self.retranslateUi(ps_list)
        QtCore.QMetaObject.connectSlotsByName(ps_list)

    def retranslateUi(self, ps_list):
        _translate = QtCore.QCoreApplication.translate
        ps_list.setWindowTitle(_translate("ps_list", "Frame"))
        self.app_search.setTitle(_translate("ps_list", "快速查找"))
        self.PushButton.setText(_translate("ps_list", "设为默认输入法"))
        self.TextEdit.setPlaceholderText(_translate("ps_list", "操作数据..."))
    def set_search(self,input_list:list):
        self.completer = QtWidgets.QCompleter(input_list, self.search_edit)
        self.completer.setCaseSensitivity(Qt.CaseInsensitive)
        self.completer.setMaxVisibleItems(10)
        self.completer.setFilterMode(QtCore.Qt.MatchContains)
        self.search_edit.setCompleter(self.completer)